name: Payments Tests CI

on:
  pull_request:
    paths:
      - "payments/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run payments tests
        run: cd payments && npm install && npm run test:ci
