

name: Tickets Tests CI

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        
      - name: Run tickets tests
        run: cd tickets && npm install && npm run test:ci

